### ISSUE TITLE
animeworldbd.com is dead

### ISSUE THREAD

**Issue by uae2ae** [anshumanv/awesome-anime-sources#40]
Looks like animeworldbd.com is dead. And their latest post is from their [tumblr](https://animeworldbd.tumblr.com/archive) blog in December 2017, the same with [twitter](https://twitter.com/animeworldbdcom) too.

**Comment by anshumanv** [comment]
Missed this issue,

Thanks for the report! Can you PR and remove it?

**Comment by toprak** [comment]
Deleted.
