### ISSUE TITLE
AnimeKayo and AnimeKaizoku

### ISSUE THREAD

**Issue by sethazazel** [anshumanv/awesome-anime-sources#43]
Please add animekayo.com to "Download Encoded MKV format" and move animekaizoku.com from "Anime" to "Download Encoded MKV format"

**Comment by sethazazel** [comment]
I tried to create a pull request for this. It is my first pull request. I hope i am doing everything right.

**Comment by anshumanv** [comment]
Hi @sethazazel, thank you! Really appreciate your effort :)
