### ISSUE TITLE
Sayonara Kissanime 👋 

### ISSUE THREAD

**Issue by anshumanv** [anshumanv/awesome-anime-sources#45]
Remove kissanime as it's 
![image](https://user-images.githubusercontent.com/21009455/90331886-c25b1a80-dfd5-11ea-9b9e-6db5c115ed99.png)

@starkblaze01 can you take care of this?

**Comment by starkblaze01** [comment]
@anshumanv, 😞  You want me to **commit** this crime.

**Comment by anshumanv** [comment]
Yes precisely, squash that link from this list
